SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `advance_assignment` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `report_global_advance` tinyint(1) DEFAULT NULL,
  `advance_type_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `advance_assignment_template` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `advance_type_id` bigint(20) DEFAULT NULL,
  `order_element_template_id` bigint(20) DEFAULT NULL,
  `report_global_advance` tinyint(1) DEFAULT NULL,
  `max_value` decimal(19,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `advance_measurement` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `date` date DEFAULT NULL,
  `value` decimal(19,2) DEFAULT NULL,
  `advance_assignment_id` bigint(20) DEFAULT NULL,
  `communication_date` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `advance_type` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `unit_name` varchar(255) DEFAULT NULL,
  `default_max_value` decimal(19,4) DEFAULT NULL,
  `updatable` tinyint(1) DEFAULT NULL,
  `unit_precision` decimal(19,4) DEFAULT NULL,
  `active` tinyint(1) DEFAULT NULL,
  `percentage` tinyint(1) DEFAULT NULL,
  `quality_form` tinyint(1) DEFAULT NULL,
  `read_only` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `all_criterions` (
  `generic_resource_allocation_id` bigint(20) NOT NULL,
  `criterion_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `assignment_function` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `base_calendar` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `code_autogenerated` tinyint(1) DEFAULT NULL,
  `last_sequence_code` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `calendar_availability` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `base_calendar_id` bigint(20) DEFAULT NULL,
  `position_in_calendar` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `calendar_data` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `parent` bigint(20) DEFAULT NULL,
  `expiring_date` date DEFAULT NULL,
  `base_calendar_id` bigint(20) DEFAULT NULL,
  `position_in_calendar` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `calendar_exception` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `date` date DEFAULT NULL,
  `standard_effort` int(11) DEFAULT NULL,
  `calendar_exception_id` bigint(20) DEFAULT NULL,
  `base_calendar_id` bigint(20) DEFAULT NULL,
  `allowed_extra_effort` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `calendar_exception_type` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `code_autogenerated` tinyint(1) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `color` varchar(255) DEFAULT NULL,
  `standard_effort` int(11) DEFAULT NULL,
  `allowed_extra_effort` int(11) DEFAULT NULL,
  `updatable` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `capacity_per_day` (
  `base_calendar_id` bigint(20) NOT NULL,
  `standard_effort` int(11) DEFAULT NULL,
  `day_id` int(11) NOT NULL,
  `allowed_extra_effort` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `configuration` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `configuration_id` bigint(20) DEFAULT NULL,
  `company_code` varchar(255) DEFAULT NULL,
  `generate_code_for_cost_category` tinyint(1) NOT NULL,
  `generate_code_for_calendar_exception_type` tinyint(1) NOT NULL,
  `generate_code_for_work_report_type` tinyint(1) NOT NULL,
  `generate_code_for_criterion` tinyint(1) NOT NULL,
  `generate_code_for_label` tinyint(1) NOT NULL,
  `generate_code_for_work_report` tinyint(1) NOT NULL,
  `generate_code_for_resources` tinyint(1) NOT NULL,
  `generate_code_for_types_of_work_hours` tinyint(1) NOT NULL,
  `generate_code_for_material_categories` tinyint(1) NOT NULL,
  `generate_code_for_unit_types` tinyint(1) NOT NULL,
  `generate_code_for_base_calendars` tinyint(1) NOT NULL,
  `monte_carlo_method_tab_visible` tinyint(1) NOT NULL,
  `progress_type` int(11) DEFAULT NULL,
  `company_logo_url` varchar(255) DEFAULT NULL,
  `scenarios_visible` tinyint(1) DEFAULT NULL,
  `changed_default_admin_password` tinyint(1) NOT NULL,
  `changed_default_wsreader_password` tinyint(1) NOT NULL,
  `changed_default_wswriter_password` tinyint(1) NOT NULL,
  `ldap_host` varchar(255) DEFAULT NULL,
  `ldap_port` varchar(5) DEFAULT NULL,
  `ldap_base` varchar(255) DEFAULT NULL,
  `ldap_userdn` varchar(255) DEFAULT NULL,
  `ldap_password` varchar(255) DEFAULT NULL,
  `ldap_userid` varchar(255) DEFAULT NULL,
  `ldap_save_password_db` tinyint(1) NOT NULL,
  `ldap_auth_enabled` tinyint(1) NOT NULL,
  `ldap_save_roles_db` tinyint(1) NOT NULL,
  `ldap_group_path` varchar(255) DEFAULT NULL,
  `ldap_role_property` varchar(255) DEFAULT NULL,
  `ldap_search_query` varchar(255) DEFAULT NULL,
  `enabled_autocomplete_login` tinyint(1) NOT NULL,
  `ldap_group_strategy` tinyint(1) NOT NULL,
  `check_new_version_enabled` tinyint(1) NOT NULL,
  `allow_to_gather_usage_stats_enabled` tinyint(1) NOT NULL,
  `generate_code_for_expense_sheets` tinyint(1) NOT NULL,
  `currency_code` varchar(255) NOT NULL,
  `currency_symbol` varchar(255) NOT NULL,
  `personal_timesheets_type_of_work_hours` bigint(20) DEFAULT NULL,
  `changed_default_wssubcontracting_password` tinyint(1) NOT NULL,
  `changed_default_manager_password` tinyint(1) NOT NULL,
  `changed_default_hresources_password` tinyint(1) NOT NULL,
  `changed_default_outsourcing_password` tinyint(1) NOT NULL,
  `changed_default_reports_password` tinyint(1) NOT NULL,
  `personal_timesheets_periodicity` int(11) DEFAULT NULL,
  `max_users` int(11) DEFAULT NULL,
  `max_resources` int(11) DEFAULT NULL,
  `seconds_planning_warning` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `configuration_roles_ldap` (
  `role_libreplan` varchar(255) NOT NULL,
  `role_ldap` varchar(255) NOT NULL,
  `id_configuration` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `connector` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `connector_property` (
  `connector_id` bigint(20) NOT NULL,
  `connector_property_position` int(11) NOT NULL,
  `property_key` varchar(255) NOT NULL,
  `property_value` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `consolidated_value` (
  `id` bigint(20) NOT NULL,
  `consolidated_value_type` varchar(255) NOT NULL,
  `version` bigint(20) NOT NULL,
  `date` date DEFAULT NULL,
  `value` decimal(19,2) DEFAULT NULL,
  `task_end_date` date DEFAULT NULL,
  `consolidation_id` bigint(20) DEFAULT NULL,
  `advance_measurement_id` bigint(20) DEFAULT NULL,
  `task_end_date_effort_duration` int(11) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `consolidation` (
  `id` bigint(20) NOT NULL,
  `consolidation_type` varchar(255) NOT NULL,
  `version` bigint(20) NOT NULL,
  `dir_advance_assignment_id` bigint(20) DEFAULT NULL,
  `ind_advance_assignment_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `cost_category` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `code_autogenerated` tinyint(1) NOT NULL,
  `last_hour_cost_sequence_code` int(11) NOT NULL,
  `enabled` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `criterion` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `predefined_criterion_internal_name` varchar(255) DEFAULT NULL,
  `active` tinyint(1) DEFAULT NULL,
  `id_criterion_type` bigint(20) NOT NULL,
  `parent` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `criterion_requirement` (
  `id` bigint(20) NOT NULL,
  `criterion_requirement_type` varchar(255) NOT NULL,
  `version` bigint(20) NOT NULL,
  `hours_group_id` bigint(20) DEFAULT NULL,
  `order_element_id` bigint(20) DEFAULT NULL,
  `order_element_template_id` bigint(20) DEFAULT NULL,
  `criterion_id` bigint(20) DEFAULT NULL,
  `parent` bigint(20) DEFAULT NULL,
  `valid` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `criterion_satisfaction` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `start_date` date DEFAULT NULL,
  `finish_date` date DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `criterion` bigint(20) NOT NULL,
  `resource` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `criterion_type` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `predefined_type_internal_name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `allow_simultaneous_criterions_per_resource` tinyint(1) DEFAULT NULL,
  `allow_hierarchy` tinyint(1) DEFAULT NULL,
  `last_criterion_sequence_code` int(11) DEFAULT NULL,
  `enabled` tinyint(1) DEFAULT NULL,
  `code_autogenerated` tinyint(1) NOT NULL,
  `resource` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `customer_communication` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `deadline` datetime DEFAULT NULL,
  `communication_type` int(11) DEFAULT NULL,
  `communication_date` datetime DEFAULT NULL,
  `reviewed` tinyint(1) DEFAULT NULL,
  `order_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `DATABASECHANGELOG` (
  `ID` varchar(63) NOT NULL,
  `AUTHOR` varchar(63) NOT NULL,
  `FILENAME` varchar(200) NOT NULL,
  `DATEEXECUTED` datetime NOT NULL,
  `ORDEREXECUTED` int(11) NOT NULL,
  `EXECTYPE` varchar(10) NOT NULL,
  `MD5SUM` varchar(35) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `COMMENTS` varchar(255) DEFAULT NULL,
  `TAG` varchar(255) DEFAULT NULL,
  `LIQUIBASE` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `DATABASECHANGELOGLOCK` (
  `ID` int(11) NOT NULL,
  `LOCKED` tinyint(1) NOT NULL,
  `LOCKGRANTED` datetime DEFAULT NULL,
  `LOCKEDBY` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `day_assignment` (
  `id` bigint(20) NOT NULL,
  `day_assignment_type` varchar(255) NOT NULL,
  `version` bigint(20) NOT NULL,
  `duration` int(11) NOT NULL,
  `consolidated` tinyint(1) DEFAULT NULL,
  `day` date NOT NULL,
  `resource_id` bigint(20) NOT NULL,
  `specific_container_id` bigint(20) DEFAULT NULL,
  `generic_container_id` bigint(20) DEFAULT NULL,
  `derived_container_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `deadline_communication` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `save_date` datetime DEFAULT NULL,
  `deliver_date` datetime DEFAULT NULL,
  `order_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `dependency` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `origin` bigint(20) DEFAULT NULL,
  `destination` bigint(20) DEFAULT NULL,
  `queue_dependency` bigint(20) DEFAULT NULL,
  `type` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `derived_allocation` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `resource_allocation_id` bigint(20) DEFAULT NULL,
  `configurationunit` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `derived_day_assignments_container` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `derived_allocation_id` bigint(20) DEFAULT NULL,
  `scenario` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `description_values` (
  `description_value_id` bigint(20) NOT NULL,
  `fieldname` varchar(255) DEFAULT NULL,
  `value` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `description_values_in_line` (
  `description_value_id` bigint(20) NOT NULL,
  `field_name` varchar(255) DEFAULT NULL,
  `value` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `direct_advance_assignment` (
  `advance_assignment_id` bigint(20) NOT NULL,
  `direct_order_element_id` bigint(20) DEFAULT NULL,
  `max_value` decimal(19,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `end_date_communication` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `save_date` datetime DEFAULT NULL,
  `end_date` datetime DEFAULT NULL,
  `communication_date` datetime DEFAULT NULL,
  `order_id` bigint(20) DEFAULT NULL,
  `subcontracted_task_data_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `entity_sequence` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `entity_name` int(11) DEFAULT NULL,
  `prefix` varchar(255) DEFAULT NULL,
  `last_value` int(11) DEFAULT NULL,
  `number_of_digits` int(11) DEFAULT NULL,
  `active` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `expense_sheet` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `code_autogenerated` tinyint(1) DEFAULT NULL,
  `first_expense` date DEFAULT NULL,
  `last_expense` date DEFAULT NULL,
  `total` decimal(19,2) DEFAULT NULL,
  `description` text,
  `last_expense_sheet_line_sequence_code` int(11) DEFAULT NULL,
  `personal` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `expense_sheet_line` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `value` decimal(19,2) DEFAULT NULL,
  `concept` varchar(255) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `order_element_id` bigint(20) DEFAULT NULL,
  `resource_id` bigint(20) DEFAULT NULL,
  `expense_sheet_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `external_company` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `nif` varchar(255) DEFAULT NULL,
  `client` tinyint(1) DEFAULT NULL,
  `subcontractor` tinyint(1) DEFAULT NULL,
  `interacts_with_applications` tinyint(1) DEFAULT NULL,
  `app_uri` varchar(255) DEFAULT NULL,
  `our_company_login` varchar(255) DEFAULT NULL,
  `our_company_password` varchar(255) DEFAULT NULL,
  `company_user` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `general_log` (
  `event_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_host` mediumtext NOT NULL,
  `thread_id` bigint(20) NOT NULL,
  `server_id` int(11) NOT NULL,
  `command_type` varchar(64) NOT NULL,
  `argument` mediumtext NOT NULL
) ENGINE=CSV DEFAULT CHARSET=utf8 COMMENT='Log mysql';

CREATE TABLE `generic_day_assignments_container` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `resource_allocation_id` bigint(20) DEFAULT NULL,
  `scenario` bigint(20) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `duration_start_in_first_day` int(11) DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `duration_in_last_day` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `generic_resource_allocation` (
  `resource_allocation_id` bigint(20) NOT NULL,
  `resource_type` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `heading_field` (
  `heading_id` bigint(20) NOT NULL,
  `fieldname` varchar(255) DEFAULT NULL,
  `length` int(11) DEFAULT NULL,
  `positionnumber` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `hibernate_unique_key` (
  `next_hi` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `hours_group` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `resource_type` varchar(255) DEFAULT NULL,
  `working_hours` int(11) NOT NULL,
  `percentage` decimal(19,2) DEFAULT NULL,
  `fixed_percentage` tinyint(1) DEFAULT NULL,
  `parent_order_line` bigint(20) DEFAULT NULL,
  `order_line_template` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `hour_cost` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `price_cost` decimal(19,2) DEFAULT NULL,
  `init_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `type_of_work_hours_id` bigint(20) DEFAULT NULL,
  `cost_category_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `indirect_advance_assignment` (
  `advance_assignment_id` bigint(20) NOT NULL,
  `indirect_order_element_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `job_scheduler_configuration` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `job_group` varchar(255) NOT NULL,
  `job_name` varchar(255) NOT NULL,
  `cron_expression` varchar(255) NOT NULL,
  `job_class_name` int(11) NOT NULL,
  `connector_name` varchar(255) DEFAULT NULL,
  `schedule` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `label` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `label_type_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `label_type` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `code_autogenerated` tinyint(1) NOT NULL,
  `last_label_sequence_code` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `limiting_resource_queue` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `resource_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `limiting_resource_queue_dependency` (
  `id` bigint(20) NOT NULL,
  `type` int(11) DEFAULT NULL,
  `origin_queue_element_id` bigint(20) DEFAULT NULL,
  `destiny_queue_element_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `limiting_resource_queue_element` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `resource_allocation_id` bigint(20) DEFAULT NULL,
  `limiting_resource_queue_id` bigint(20) DEFAULT NULL,
  `earlier_start_date_because_of_gantt` datetime DEFAULT NULL,
  `earliest_end_date_because_of_gantt` datetime DEFAULT NULL,
  `creation_timestamp` bigint(20) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `start_hour` int(11) DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `end_hour` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `line_field` (
  `heading_id` bigint(20) NOT NULL,
  `fieldname` varchar(255) DEFAULT NULL,
  `length` int(11) DEFAULT NULL,
  `positionnumber` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `machine` (
  `machine_id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `machine_configuration_unit_required_criterions` (
  `id` bigint(20) NOT NULL,
  `criterion_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `machine_workers_configuration_unit` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `name` varchar(255) NOT NULL,
  `alpha` decimal(19,2) NOT NULL,
  `machine` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `machine_worker_assignment` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `start_date` datetime DEFAULT NULL,
  `finish_date` datetime DEFAULT NULL,
  `configuration_id` bigint(20) NOT NULL,
  `worker_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `manual_function` (
  `assignment_function_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `material` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `default_unit_price` decimal(19,2) DEFAULT NULL,
  `unit_type` bigint(20) DEFAULT NULL,
  `disabled` tinyint(1) DEFAULT NULL,
  `category_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `material_assigment` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `units` decimal(19,2) DEFAULT NULL,
  `unit_price` decimal(19,2) DEFAULT NULL,
  `material_id` bigint(20) DEFAULT NULL,
  `estimated_availability` datetime DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `order_element_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `material_assigment_template` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `units` decimal(19,2) DEFAULT NULL,
  `unit_price` decimal(19,2) DEFAULT NULL,
  `material_id` bigint(20) DEFAULT NULL,
  `order_element_template_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `material_category` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `code_autogenerated` tinyint(1) NOT NULL,
  `last_material_sequence_code` int(11) NOT NULL,
  `parent_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_authorization` (
  `id` bigint(20) NOT NULL,
  `order_authorization_subclass` varchar(255) NOT NULL,
  `version` bigint(20) NOT NULL,
  `authorization_type` varchar(255) NOT NULL,
  `order_id` bigint(20) DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL,
  `profile_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_element` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text,
  `code` varchar(255) DEFAULT NULL,
  `init_date` datetime DEFAULT NULL,
  `deadline` datetime DEFAULT NULL,
  `last_advance_meausurement_for_spreading` decimal(19,2) DEFAULT NULL,
  `dirty_last_advance_measurement_for_spreading` tinyint(1) DEFAULT NULL,
  `parent` bigint(20) DEFAULT NULL,
  `template` bigint(20) DEFAULT NULL,
  `external_code` varchar(255) DEFAULT NULL,
  `position_in_container` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_element_label` (
  `order_element_id` bigint(20) NOT NULL,
  `label_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_element_template` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text,
  `start_as_days_from_beginning` int(11) DEFAULT NULL,
  `deadline_as_days_from_beginning` int(11) DEFAULT NULL,
  `scheduling_state_type` int(11) DEFAULT NULL,
  `parent` bigint(20) DEFAULT NULL,
  `position_in_container` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_element_template_label` (
  `order_element_template_id` bigint(20) NOT NULL,
  `label_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_element_template_quality_form` (
  `order_element_template_id` bigint(20) NOT NULL,
  `quality_form_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_line` (
  `order_element_id` bigint(20) NOT NULL,
  `last_hours_group_sequence_code` int(11) DEFAULT NULL,
  `budget` decimal(19,2) NOT NULL DEFAULT '0.00'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_line_group` (
  `order_element_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_line_group_template` (
  `group_template_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_line_template` (
  `order_line_template_id` bigint(20) NOT NULL,
  `last_hours_group_sequence_code` int(11) DEFAULT NULL,
  `budget` decimal(19,2) NOT NULL DEFAULT '0.00'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_sync_info` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `last_sync_date` datetime NOT NULL,
  `key` varchar(255) NOT NULL,
  `connector_name` varchar(255) NOT NULL,
  `order_element_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_table` (
  `order_element_id` bigint(20) NOT NULL,
  `responsible` varchar(255) DEFAULT NULL,
  `dependencies_constraints_have_priority` tinyint(1) DEFAULT NULL,
  `code_autogenerated` tinyint(1) DEFAULT NULL,
  `last_order_element_sequence_code` int(11) DEFAULT NULL,
  `work_budget` decimal(19,2) DEFAULT NULL,
  `materials_budget` decimal(19,2) DEFAULT NULL,
  `total_hours` int(11) DEFAULT NULL,
  `customer_reference` varchar(255) DEFAULT NULL,
  `external_code` varchar(255) DEFAULT NULL,
  `state` int(11) DEFAULT NULL,
  `customer` bigint(20) DEFAULT NULL,
  `base_calendar_id` bigint(20) DEFAULT NULL,
  `scheduling_mode` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_template` (
  `order_template_id` bigint(20) NOT NULL,
  `base_calendar_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order_version` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `modification_by_owner_timestamp` datetime DEFAULT NULL,
  `ownerscenario` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `planning_data` (
  `planning_data_id` bigint(20) NOT NULL,
  `progress_by_duration` decimal(19,6) DEFAULT NULL,
  `progress_by_num_hours` decimal(19,6) DEFAULT NULL,
  `progress_all_by_num_hours` decimal(19,6) DEFAULT NULL,
  `version` bigint(20) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `profile_roles` (
  `profile_id` bigint(20) NOT NULL,
  `role` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `profile_table` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `profile_name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `quality_form` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `quality_form_type` int(11) DEFAULT NULL,
  `report_advance` tinyint(1) DEFAULT NULL,
  `advance_type_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `quality_form_items` (
  `quality_form_id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `percentage` decimal(19,2) DEFAULT NULL,
  `position` int(11) DEFAULT NULL,
  `idx` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `resource` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `code_autogenerated` tinyint(1) NOT NULL,
  `base_calendar_id` bigint(20) DEFAULT NULL,
  `resource_type` varchar(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `resources_cost_category_assignment` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `init_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `cost_category_id` bigint(20) DEFAULT NULL,
  `resource_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `resource_allocation` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `resources_per_day` decimal(19,2) DEFAULT NULL,
  `intended_total_hours` int(11) DEFAULT NULL,
  `task` bigint(20) DEFAULT NULL,
  `assignment_function` bigint(20) DEFAULT NULL,
  `intended_resources_per_day` decimal(19,2) DEFAULT NULL,
  `intended_total_assignment` int(11) DEFAULT '0',
  `intended_non_consolidated_effort` int(11) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `resource_calendar` (
  `base_calendar_id` bigint(20) NOT NULL,
  `capacity` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `roles_table` (
  `user_id` bigint(20) NOT NULL,
  `role` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `scenario` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `last_not_owned_reassignations_time_stamp` datetime DEFAULT NULL,
  `predecessor` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `scenario_orders` (
  `order_id` bigint(20) NOT NULL,
  `order_version_id` bigint(20) NOT NULL,
  `scenario_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `scheduling_data_for_version` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `scheduling_state_type` int(11) DEFAULT NULL,
  `order_element_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `scheduling_states_by_order_version` (
  `order_element_id` bigint(20) NOT NULL,
  `scheduling_state_for_version_id` bigint(20) NOT NULL,
  `order_version_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `sigmoid_function` (
  `assignment_function_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `specific_day_assignments_container` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `resource_allocation_id` bigint(20) DEFAULT NULL,
  `scenario` bigint(20) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `duration_start_in_first_day` int(11) DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `duration_in_last_day` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `specific_resource_allocation` (
  `resource_allocation_id` bigint(20) NOT NULL,
  `resource` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `stretches` (
  `assignment_function_id` bigint(20) NOT NULL,
  `length_percentage` decimal(19,2) NOT NULL,
  `amount_work_percentage` decimal(19,2) NOT NULL,
  `stretch_position` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `stretches_function` (
  `assignment_function_id` bigint(20) NOT NULL,
  `type` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `subcontracted_task_data` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `external_company` bigint(20) DEFAULT NULL,
  `subcontratation_date` datetime DEFAULT NULL,
  `subcontract_communication_date` datetime DEFAULT NULL,
  `work_description` varchar(255) DEFAULT NULL,
  `subcontract_price` decimal(19,2) DEFAULT NULL,
  `subcontracted_code` varchar(255) DEFAULT NULL,
  `node_without_children_exported` tinyint(1) DEFAULT NULL,
  `labels_exported` tinyint(1) DEFAULT NULL,
  `material_assignments_exported` tinyint(1) DEFAULT NULL,
  `hours_groups_exported` tinyint(1) DEFAULT NULL,
  `state` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `subcontractor_communication` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `communication_type` int(11) DEFAULT NULL,
  `communication_date` datetime DEFAULT NULL,
  `reviewed` tinyint(1) DEFAULT NULL,
  `subcontracted_task_data` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `subcontractor_communication_values` (
  `subcontractor_communication_id` bigint(20) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `progress` decimal(19,2) DEFAULT NULL,
  `idx` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `subcontractor_deliver_date` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `save_date` datetime DEFAULT NULL,
  `subcontractor_deliver_date` datetime DEFAULT NULL,
  `communication_date` datetime DEFAULT NULL,
  `subcontracted_task_data_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `sum_charged_effort` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `direct_charged_effort` int(11) DEFAULT NULL,
  `indirect_charged_effort` int(11) DEFAULT NULL,
  `order_element` bigint(20) DEFAULT NULL,
  `first_timesheet_date` datetime DEFAULT NULL,
  `last_timesheet_date` datetime DEFAULT NULL,
  `finished_timesheets` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `sum_expenses` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `order_element_id` bigint(20) DEFAULT NULL,
  `total_direct_expenses` decimal(19,2) DEFAULT NULL,
  `total_indirect_expenses` decimal(19,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `task` (
  `task_element_id` bigint(20) NOT NULL,
  `calculated_value` int(11) DEFAULT NULL,
  `constraint_type` int(11) DEFAULT NULL,
  `constraint_date` date DEFAULT NULL,
  `workable_days` int(11) DEFAULT NULL,
  `allocation_direction` int(11) DEFAULT NULL,
  `subcontrated_task_data_id` bigint(20) DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `constraint_date_effort_duration` int(11) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `task_element` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `notes` text,
  `start_date` date NOT NULL,
  `start_day_duration` int(11) DEFAULT NULL,
  `end_date` date NOT NULL,
  `end_day_duration` int(11) DEFAULT NULL,
  `deadline` date DEFAULT NULL,
  `advance_percentage` decimal(19,4) DEFAULT NULL,
  `sum_of_assigned_effort` int(11) DEFAULT NULL,
  `parent` bigint(20) DEFAULT NULL,
  `base_calendar_id` bigint(20) DEFAULT NULL,
  `position_in_parent` int(11) DEFAULT NULL,
  `updated_from_timesheets` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `task_group` (
  `task_element_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `task_milestone` (
  `task_element_id` bigint(20) NOT NULL,
  `constraint_type` int(11) DEFAULT NULL,
  `constraint_date` date DEFAULT NULL,
  `constraint_date_effort_duration` int(11) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `task_quality_form` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `quality_form_id` bigint(20) DEFAULT NULL,
  `order_element_id` bigint(20) DEFAULT NULL,
  `report_advance` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `task_quality_form_items` (
  `task_quality_form_id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `percentage` decimal(19,2) DEFAULT NULL,
  `position` int(11) DEFAULT NULL,
  `passed` tinyint(1) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `idx` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `task_source` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `schedulingdata` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `task_source_hours_groups` (
  `task_source_id` bigint(20) NOT NULL,
  `hours_group_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `type_of_work_hours` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  `default_price` decimal(19,2) DEFAULT NULL,
  `enabled` tinyint(1) DEFAULT NULL,
  `code_autogenerated` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `unit_type` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `measure` varchar(255) DEFAULT NULL,
  `code_autogenerated` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user_profiles` (
  `user_id` bigint(20) NOT NULL,
  `profile_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user_table` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `login_name` varchar(255) NOT NULL,
  `password` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `disabled` tinyint(1) DEFAULT NULL,
  `lastconnectedscenario` bigint(20) DEFAULT NULL,
  `libreplan_user` tinyint(1) DEFAULT NULL,
  `application_language` int(11) DEFAULT '0',
  `expand_company_planning_view_charts` tinyint(1) NOT NULL,
  `expand_order_planning_view_charts` tinyint(1) NOT NULL,
  `expand_resource_load_view_charts` tinyint(1) NOT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `projects_filter_period_since` int(11) DEFAULT NULL,
  `projects_filter_period_to` int(11) DEFAULT NULL,
  `resources_load_filter_period_since` int(11) DEFAULT NULL,
  `resources_load_filter_period_to` int(11) DEFAULT NULL,
  `projects_filter_label_id` bigint(20) DEFAULT NULL,
  `resources_load_filter_criterion_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `virtual_worker` (
  `virtual_worker_id` bigint(20) NOT NULL,
  `observations` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `worker` (
  `worker_id` bigint(20) NOT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `surname` varchar(255) DEFAULT NULL,
  `nif` varchar(255) DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `workreportslines_labels` (
  `work_report_line_id` bigint(20) NOT NULL,
  `label_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `workreports_labels` (
  `work_report_id` bigint(20) NOT NULL,
  `label_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `work_report` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `date` datetime DEFAULT NULL,
  `code_autogenerated` tinyint(1) NOT NULL,
  `last_work_report_line_sequence_code` int(11) DEFAULT NULL,
  `ork_report_type_id` bigint(20) NOT NULL,
  `resource_id` bigint(20) DEFAULT NULL,
  `order_element_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `work_report_label_type_assigment` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `labels_shared_by_lines` tinyint(1) DEFAULT NULL,
  `position_number` int(11) DEFAULT NULL,
  `label_type_id` bigint(20) DEFAULT NULL,
  `label_id` bigint(20) DEFAULT NULL,
  `work_report_type_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `work_report_line` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `effort` int(11) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `clock_start` int(11) DEFAULT NULL,
  `clock_finish` int(11) DEFAULT NULL,
  `work_report_id` bigint(20) DEFAULT NULL,
  `resource_id` bigint(20) NOT NULL,
  `order_element_id` bigint(20) NOT NULL,
  `type_work_hours_id` bigint(20) NOT NULL,
  `finished` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `work_report_type` (
  `id` bigint(20) NOT NULL,
  `version` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  `date_is_shared_by_lines` tinyint(1) DEFAULT NULL,
  `resource_is_shared_in_lines` tinyint(1) DEFAULT NULL,
  `order_element_is_shared_in_lines` tinyint(1) DEFAULT NULL,
  `code_autogenerated` tinyint(1) NOT NULL,
  `hours_management` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `advance_assignment`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkd4192eaab216ed4c` (`advance_type_id`);

ALTER TABLE `advance_assignment_template`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkd9bfae6fb216ed4c` (`advance_type_id`),
  ADD KEY `fkd9bfae6f19b9dfde` (`order_element_template_id`);

ALTER TABLE `advance_measurement`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkdaba2f7fa9e53843` (`advance_assignment_id`);

ALTER TABLE `advance_type`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `advance_type_unit_name_key` (`unit_name`);

ALTER TABLE `all_criterions`
  ADD PRIMARY KEY (`generic_resource_allocation_id`,`criterion_id`),
  ADD KEY `fk7980035061f02c44` (`criterion_id`);

ALTER TABLE `assignment_function`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `base_calendar`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `base_calendar_code_key` (`code`);

ALTER TABLE `calendar_availability`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `calendar_availability_code_key` (`code`),
  ADD KEY `fk557738bca44abee3` (`base_calendar_id`);

ALTER TABLE `calendar_data`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `calendar_data_code_key` (`code`),
  ADD KEY `fk74fc040ba44abee3` (`base_calendar_id`),
  ADD KEY `fk74fc040b7fa34e3f` (`parent`);

ALTER TABLE `calendar_exception`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `calendar_exception_code_key` (`code`),
  ADD KEY `fka215508ea44abee3` (`base_calendar_id`),
  ADD KEY `fka215508eadad7e51` (`calendar_exception_id`);

ALTER TABLE `calendar_exception_type`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `calendar_exception_type_code_key` (`code`),
  ADD UNIQUE KEY `calendar_exception_type_name_key` (`name`);

ALTER TABLE `capacity_per_day`
  ADD PRIMARY KEY (`base_calendar_id`,`day_id`);

ALTER TABLE `configuration`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk733374f6cc119699` (`configuration_id`),
  ADD KEY `configuration_type_of_work_hours_fkey` (`personal_timesheets_type_of_work_hours`);

ALTER TABLE `configuration_roles_ldap`
  ADD PRIMARY KEY (`role_libreplan`,`role_ldap`),
  ADD KEY `id_configuration_fkey` (`id_configuration`);

ALTER TABLE `connector`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `connector_property`
  ADD PRIMARY KEY (`connector_id`,`connector_property_position`);

ALTER TABLE `consolidated_value`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk35588e2db96bba28` (`advance_measurement_id`),
  ADD KEY `fk35588e2d3ae24ff8` (`consolidation_id`);

ALTER TABLE `consolidation`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkc9400e2c9f1d6611` (`dir_advance_assignment_id`),
  ADD KEY `fkc9400e2c430ea1de` (`ind_advance_assignment_id`);

ALTER TABLE `cost_category`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `cost_category_code_key` (`code`),
  ADD UNIQUE KEY `cost_category_name_key` (`name`);

ALTER TABLE `criterion`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `criterion_code_key` (`code`),
  ADD UNIQUE KEY `criterion_name_key` (`id_criterion_type`,`name`),
  ADD KEY `fk16e20ea13a156175` (`parent`);

ALTER TABLE `criterion_requirement`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkef395fa561f02c44` (`criterion_id`),
  ADD KEY `fkef395fa5e036cfed` (`hours_group_id`),
  ADD KEY `fkef395fa5efda874f` (`order_element_id`),
  ADD KEY `fkef395fa519b9dfde` (`order_element_template_id`),
  ADD KEY `fkef395fa5f41d57f2` (`parent`);

ALTER TABLE `criterion_satisfaction`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `criterion_satisfaction_code_key` (`code`),
  ADD KEY `fk225ff96a8c4c676c` (`criterion`),
  ADD KEY `fk225ff96aeae850b2` (`resource`);

ALTER TABLE `criterion_type`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `criterion_type_code_key` (`code`),
  ADD UNIQUE KEY `criterion_type_name_key` (`name`);

ALTER TABLE `customer_communication`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `DATABASECHANGELOG`
  ADD PRIMARY KEY (`ID`,`AUTHOR`,`FILENAME`);

ALTER TABLE `DATABASECHANGELOGLOCK`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `day_assignment`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkbb493f50510e7a78` (`derived_container_id`),
  ADD KEY `fkbb493f5019256004` (`generic_container_id`),
  ADD KEY `fkbb493f5048d21790` (`resource_id`),
  ADD KEY `fkbb493f50756348a8` (`specific_container_id`);

ALTER TABLE `deadline_communication`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `dependency`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkfe6ed34be838f362` (`destination`),
  ADD KEY `fkfe6ed34b1545e7a` (`origin`),
  ADD KEY `fkfe6ed34b9e788f90` (`queue_dependency`);

ALTER TABLE `derived_allocation`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkf0260c4287b470f0` (`configurationunit`),
  ADD KEY `fkf0260c4275ed79ba` (`resource_allocation_id`);

ALTER TABLE `derived_day_assignments_container`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkb83176c31b8e7cf2` (`derived_allocation_id`),
  ADD KEY `fkb83176c3421c7cf4` (`scenario`);

ALTER TABLE `description_values`
  ADD KEY `fk7d1ee2c5fec79eb0` (`description_value_id`);

ALTER TABLE `description_values_in_line`
  ADD KEY `fk1e6bf5475c390c4` (`description_value_id`);

ALTER TABLE `direct_advance_assignment`
  ADD PRIMARY KEY (`advance_assignment_id`),
  ADD KEY `fk172a16c0a1127ce5` (`direct_order_element_id`);

ALTER TABLE `end_date_communication`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `entity_sequence`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `expense_sheet`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `expense_sheet_line`
  ADD PRIMARY KEY (`id`),
  ADD KEY `expense_sheet_line_order_element_fkey` (`order_element_id`),
  ADD KEY `expense_sheet_line_resource_fkey` (`resource_id`),
  ADD KEY `expense_sheet_line_expense_sheet_fkey` (`expense_sheet_id`);

ALTER TABLE `external_company`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `external_company_name_key` (`name`),
  ADD UNIQUE KEY `external_company_nif_key` (`nif`),
  ADD KEY `fkd8e14c09b36a6d51` (`company_user`);

ALTER TABLE `generic_day_assignments_container`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkc01655fdee970b` (`resource_allocation_id`),
  ADD KEY `fkc01655fd421c7cf4` (`scenario`);

ALTER TABLE `generic_resource_allocation`
  ADD PRIMARY KEY (`resource_allocation_id`);

ALTER TABLE `heading_field`
  ADD KEY `fk2908787d415884f6` (`heading_id`);

ALTER TABLE `hours_group`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `hours_group_code_key` (`code`),
  ADD KEY `fkd9b7594f8bdc6ac6` (`order_line_template`),
  ADD KEY `fkd9b7594f1ed629ea` (`parent_order_line`);

ALTER TABLE `hour_cost`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `hour_cost_code_key` (`code`),
  ADD KEY `fk3b9a8148c29ad8eb` (`cost_category_id`),
  ADD KEY `fk3b9a8148d5b6184d` (`type_of_work_hours_id`);

ALTER TABLE `indirect_advance_assignment`
  ADD PRIMARY KEY (`advance_assignment_id`),
  ADD KEY `fk64cbad3b8202350f` (`indirect_order_element_id`);

ALTER TABLE `job_scheduler_configuration`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `label`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `label_code_key` (`code`),
  ADD UNIQUE KEY `label_name_key` (`label_type_id`,`name`);

ALTER TABLE `label_type`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `label_type_code_key` (`code`),
  ADD UNIQUE KEY `label_type_name_key` (`name`);

ALTER TABLE `limiting_resource_queue`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `limiting_resource_queue_resource_id_key` (`resource_id`);

ALTER TABLE `limiting_resource_queue_dependency`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk59485352e42f8d29` (`destiny_queue_element_id`),
  ADD KEY `fk5948535228f2695` (`origin_queue_element_id`);

ALTER TABLE `limiting_resource_queue_element`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `limiting_resource_queue_element_resource_allocation_id_key` (`resource_allocation_id`),
  ADD KEY `fk1fc5f455bd2209e8` (`limiting_resource_queue_id`);

ALTER TABLE `line_field`
  ADD KEY `fk88eecef415884f6` (`heading_id`);

ALTER TABLE `machine`
  ADD PRIMARY KEY (`machine_id`);

ALTER TABLE `machine_configuration_unit_required_criterions`
  ADD PRIMARY KEY (`id`,`criterion_id`),
  ADD KEY `fk95548d7861f02c44` (`criterion_id`);

ALTER TABLE `machine_workers_configuration_unit`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkd47281efffeb5538` (`machine`);

ALTER TABLE `machine_worker_assignment`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fka2c1583686b2de7a` (`configuration_id`),
  ADD KEY `fka2c158369bebcf10` (`worker_id`);

ALTER TABLE `manual_function`
  ADD PRIMARY KEY (`assignment_function_id`);

ALTER TABLE `material`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `material_code_key` (`code`),
  ADD KEY `fk11d365279578651e` (`category_id`),
  ADD KEY `fk11d36527f11b2d0` (`unit_type`);

ALTER TABLE `material_assigment`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkb3e9425b5c68337` (`material_id`),
  ADD KEY `fkb3e9425efda874f` (`order_element_id`);

ALTER TABLE `material_assigment_template`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk35254354b5c68337` (`material_id`),
  ADD KEY `fk3525435419b9dfde` (`order_element_template_id`);

ALTER TABLE `material_category`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `material_category_code_key` (`code`),
  ADD KEY `fk84c66516b53669f2` (`parent_id`);

ALTER TABLE `order_authorization`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkb92b594887287288` (`order_id`),
  ADD KEY `fkb92b5948edc4db41` (`profile_id`),
  ADD KEY `fkb92b59485567ad13` (`user_id`);

ALTER TABLE `order_element`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk92271f0b1e635c19` (`parent`),
  ADD KEY `fk92271f0bd97bcc8c` (`template`);

ALTER TABLE `order_element_label`
  ADD PRIMARY KEY (`order_element_id`,`label_id`),
  ADD KEY `fke8344cc0c1c2746e` (`label_id`);

ALTER TABLE `order_element_template`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk4339b2e41638aab` (`parent`);

ALTER TABLE `order_element_template_label`
  ADD PRIMARY KEY (`order_element_template_id`,`label_id`),
  ADD KEY `fk616de2a3c1c2746e` (`label_id`);

ALTER TABLE `order_element_template_quality_form`
  ADD PRIMARY KEY (`order_element_template_id`,`quality_form_id`),
  ADD KEY `fkfe6fb5758b37665c` (`quality_form_id`);

ALTER TABLE `order_line`
  ADD PRIMARY KEY (`order_element_id`);

ALTER TABLE `order_line_group`
  ADD PRIMARY KEY (`order_element_id`);

ALTER TABLE `order_line_group_template`
  ADD PRIMARY KEY (`group_template_id`);

ALTER TABLE `order_line_template`
  ADD PRIMARY KEY (`order_line_template_id`);

ALTER TABLE `order_sync_info`
  ADD PRIMARY KEY (`id`),
  ADD KEY `order_sync_info_order_table_fkey` (`order_element_id`);

ALTER TABLE `order_table`
  ADD PRIMARY KEY (`order_element_id`),
  ADD KEY `fk75a2f39da44abee3` (`base_calendar_id`),
  ADD KEY `fk75a2f39d4ec080cf` (`customer`);

ALTER TABLE `order_template`
  ADD PRIMARY KEY (`order_template_id`),
  ADD KEY `fk6476ce4ba44abee3` (`base_calendar_id`);

ALTER TABLE `order_version`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fka391ce7a2380ca7` (`ownerscenario`);

ALTER TABLE `planning_data`
  ADD PRIMARY KEY (`planning_data_id`);

ALTER TABLE `profile_roles`
  ADD KEY `fkd557d8a7edc4db41` (`profile_id`);

ALTER TABLE `profile_table`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `profile_table_profile_name_key` (`profile_name`);

ALTER TABLE `quality_form`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `quality_form_name_key` (`name`),
  ADD KEY `fkf635cc04b216ed4c` (`advance_type_id`);

ALTER TABLE `quality_form_items`
  ADD PRIMARY KEY (`quality_form_id`,`idx`);

ALTER TABLE `resource`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `resource_code_key` (`code`),
  ADD UNIQUE KEY `resource_base_calendar_id_key` (`base_calendar_id`);

ALTER TABLE `resources_cost_category_assignment`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `resources_cost_category_assignment_code_key` (`code`),
  ADD KEY `fk27c2a216c29ad8eb` (`cost_category_id`),
  ADD KEY `fk27c2a21648d21790` (`resource_id`);

ALTER TABLE `resource_allocation`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fke8a96db115671e92` (`assignment_function`),
  ADD KEY `fke8a96db1ff61540d` (`task`);

ALTER TABLE `resource_calendar`
  ADD PRIMARY KEY (`base_calendar_id`);

ALTER TABLE `roles_table`
  ADD KEY `fk2e7e6bcc5567ad13` (`user_id`);

ALTER TABLE `scenario`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkd1c57390fd99606d` (`predecessor`);

ALTER TABLE `scenario_orders`
  ADD PRIMARY KEY (`scenario_id`,`order_id`),
  ADD KEY `fk91bbca7487287288` (`order_id`),
  ADD KEY `fk91bbca7423b85cf1` (`order_version_id`);

ALTER TABLE `scheduling_data_for_version`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk672eed98efda874f` (`order_element_id`);

ALTER TABLE `scheduling_states_by_order_version`
  ADD PRIMARY KEY (`order_element_id`,`order_version_id`),
  ADD KEY `fk84f61df123b85cf1` (`order_version_id`),
  ADD KEY `fk84f61df19bfe55d0` (`scheduling_state_for_version_id`);

ALTER TABLE `sigmoid_function`
  ADD PRIMARY KEY (`assignment_function_id`);

ALTER TABLE `specific_day_assignments_container`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkcee469987518838c` (`resource_allocation_id`),
  ADD KEY `fkcee46998421c7cf4` (`scenario`);

ALTER TABLE `specific_resource_allocation`
  ADD PRIMARY KEY (`resource_allocation_id`),
  ADD KEY `fkf0e85724eae850b2` (`resource`);

ALTER TABLE `stretches`
  ADD PRIMARY KEY (`assignment_function_id`,`stretch_position`);

ALTER TABLE `stretches_function`
  ADD PRIMARY KEY (`assignment_function_id`);

ALTER TABLE `subcontracted_task_data`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk35bc4ed63804cfa` (`external_company`);

ALTER TABLE `subcontractor_communication`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `subcontractor_deliver_date`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `sum_charged_effort`
  ADD PRIMARY KEY (`id`),
  ADD KEY `sum_charged_effort_order_element_fkey` (`order_element`);

ALTER TABLE `sum_expenses`
  ADD PRIMARY KEY (`id`),
  ADD KEY `sum_expenses_order_element_fkey` (`order_element_id`);

ALTER TABLE `task`
  ADD PRIMARY KEY (`task_element_id`),
  ADD UNIQUE KEY `task_subcontrated_task_data_id_key` (`subcontrated_task_data_id`);

ALTER TABLE `task_element`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkc631a642a44abee3` (`base_calendar_id`),
  ADD KEY `fkc631a642a5f3c581` (`parent`);

ALTER TABLE `task_group`
  ADD PRIMARY KEY (`task_element_id`);

ALTER TABLE `task_milestone`
  ADD PRIMARY KEY (`task_element_id`);

ALTER TABLE `task_quality_form`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk4356e07eefda874f` (`order_element_id`),
  ADD KEY `fk4356e07e8b37665c` (`quality_form_id`);

ALTER TABLE `task_quality_form_items`
  ADD PRIMARY KEY (`task_quality_form_id`,`idx`);

ALTER TABLE `task_source`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `task_source_schedulingdata_key` (`schedulingdata`);

ALTER TABLE `task_source_hours_groups`
  ADD PRIMARY KEY (`task_source_id`,`hours_group_id`),
  ADD KEY `fka01fe4eee036cfed` (`hours_group_id`);

ALTER TABLE `type_of_work_hours`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `type_of_work_hours_code_key` (`code`),
  ADD UNIQUE KEY `type_of_work_hours_name_key` (`name`);

ALTER TABLE `unit_type`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `unit_type_code_key` (`code`);

ALTER TABLE `user_profiles`
  ADD PRIMARY KEY (`user_id`,`profile_id`),
  ADD KEY `fkc74605deedc4db41` (`profile_id`);

ALTER TABLE `user_table`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `user_table_login_name_key` (`login_name`),
  ADD KEY `fk7358465a4cd98327` (`lastconnectedscenario`),
  ADD KEY `user_label_fkey` (`projects_filter_label_id`),
  ADD KEY `user_criterion_fkey` (`resources_load_filter_criterion_id`);

ALTER TABLE `virtual_worker`
  ADD PRIMARY KEY (`virtual_worker_id`);

ALTER TABLE `worker`
  ADD PRIMARY KEY (`worker_id`),
  ADD UNIQUE KEY `worker_user_id_key` (`user_id`);

ALTER TABLE `workreportslines_labels`
  ADD PRIMARY KEY (`work_report_line_id`,`label_id`),
  ADD KEY `fkcb8fc1cdc1c2746e` (`label_id`);

ALTER TABLE `workreports_labels`
  ADD PRIMARY KEY (`work_report_id`,`label_id`),
  ADD KEY `fkf796fbd0c1c2746e` (`label_id`);

ALTER TABLE `work_report`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `work_report_code_key` (`code`),
  ADD KEY `fkfd7aa622efda874f` (`order_element_id`),
  ADD KEY `fkfd7aa62278e4e2ea` (`ork_report_type_id`),
  ADD KEY `fkfd7aa62248d21790` (`resource_id`);

ALTER TABLE `work_report_label_type_assigment`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fkbb262920c1c2746e` (`label_id`),
  ADD KEY `fkbb262920707cd777` (`label_type_id`),
  ADD KEY `fkbb262920131853a1` (`work_report_type_id`);

ALTER TABLE `work_report_line`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `work_report_line_code_key` (`code`),
  ADD KEY `fke2af47f1efda874f` (`order_element_id`),
  ADD KEY `fke2af47f148d21790` (`resource_id`),
  ADD KEY `fke2af47f1e7e1020b` (`type_work_hours_id`),
  ADD KEY `fke2af47f1f1a3177c` (`work_report_id`);

ALTER TABLE `work_report_type`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `work_report_type_code_key` (`code`),
  ADD UNIQUE KEY `work_report_type_name_key` (`name`);


ALTER TABLE `connector`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `job_scheduler_configuration`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `advance_assignment`
  ADD CONSTRAINT `fkd4192eaab216ed4c` FOREIGN KEY (`advance_type_id`) REFERENCES `advance_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `advance_assignment_template`
  ADD CONSTRAINT `fkd9bfae6f19b9dfde` FOREIGN KEY (`order_element_template_id`) REFERENCES `order_element_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkd9bfae6fb216ed4c` FOREIGN KEY (`advance_type_id`) REFERENCES `advance_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `advance_measurement`
  ADD CONSTRAINT `fkdaba2f7f2f2d3aec` FOREIGN KEY (`advance_assignment_id`) REFERENCES `advance_assignment` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkdaba2f7fa9e53843` FOREIGN KEY (`advance_assignment_id`) REFERENCES `direct_advance_assignment` (`advance_assignment_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `all_criterions`
  ADD CONSTRAINT `fk7980035061f02c44` FOREIGN KEY (`criterion_id`) REFERENCES `criterion` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk79800350b1524a73` FOREIGN KEY (`generic_resource_allocation_id`) REFERENCES `generic_resource_allocation` (`resource_allocation_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `calendar_availability`
  ADD CONSTRAINT `fk557738bca44abee3` FOREIGN KEY (`base_calendar_id`) REFERENCES `base_calendar` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `calendar_data`
  ADD CONSTRAINT `fk74fc040b7fa34e3f` FOREIGN KEY (`parent`) REFERENCES `base_calendar` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk74fc040ba44abee3` FOREIGN KEY (`base_calendar_id`) REFERENCES `base_calendar` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `calendar_exception`
  ADD CONSTRAINT `fka215508ea44abee3` FOREIGN KEY (`base_calendar_id`) REFERENCES `base_calendar` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fka215508eadad7e51` FOREIGN KEY (`calendar_exception_id`) REFERENCES `calendar_exception_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `capacity_per_day`
  ADD CONSTRAINT `fkc405554bfd5e49bc` FOREIGN KEY (`base_calendar_id`) REFERENCES `calendar_data` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `configuration`
  ADD CONSTRAINT `configuration_type_of_work_hours_fkey` FOREIGN KEY (`personal_timesheets_type_of_work_hours`) REFERENCES `type_of_work_hours` (`id`),
  ADD CONSTRAINT `fk733374f6cc119699` FOREIGN KEY (`configuration_id`) REFERENCES `base_calendar` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `configuration_roles_ldap`
  ADD CONSTRAINT `id_configuration_fkey` FOREIGN KEY (`id_configuration`) REFERENCES `configuration` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `connector_property`
  ADD CONSTRAINT `connector_property_connector_id_fkey` FOREIGN KEY (`connector_id`) REFERENCES `connector` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `consolidated_value`
  ADD CONSTRAINT `fk35588e2d3ae24ff8` FOREIGN KEY (`consolidation_id`) REFERENCES `consolidation` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk35588e2db96bba28` FOREIGN KEY (`advance_measurement_id`) REFERENCES `advance_measurement` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `consolidation`
  ADD CONSTRAINT `fkc9400e2c430ea1de` FOREIGN KEY (`ind_advance_assignment_id`) REFERENCES `indirect_advance_assignment` (`advance_assignment_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkc9400e2c9f1d6611` FOREIGN KEY (`dir_advance_assignment_id`) REFERENCES `direct_advance_assignment` (`advance_assignment_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkc9400e2cff2b2ba3` FOREIGN KEY (`id`) REFERENCES `task` (`task_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `criterion`
  ADD CONSTRAINT `fk16e20ea114a5c61` FOREIGN KEY (`id_criterion_type`) REFERENCES `criterion_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk16e20ea13a156175` FOREIGN KEY (`parent`) REFERENCES `criterion` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `criterion_requirement`
  ADD CONSTRAINT `fkef395fa519b9dfde` FOREIGN KEY (`order_element_template_id`) REFERENCES `order_element_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkef395fa561f02c44` FOREIGN KEY (`criterion_id`) REFERENCES `criterion` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkef395fa5e036cfed` FOREIGN KEY (`hours_group_id`) REFERENCES `hours_group` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkef395fa5efda874f` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkef395fa5f41d57f2` FOREIGN KEY (`parent`) REFERENCES `criterion_requirement` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `criterion_satisfaction`
  ADD CONSTRAINT `fk225ff96a8c4c676c` FOREIGN KEY (`criterion`) REFERENCES `criterion` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk225ff96aeae850b2` FOREIGN KEY (`resource`) REFERENCES `resource` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `day_assignment`
  ADD CONSTRAINT `fkbb493f5019256004` FOREIGN KEY (`generic_container_id`) REFERENCES `generic_day_assignments_container` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkbb493f5048d21790` FOREIGN KEY (`resource_id`) REFERENCES `resource` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkbb493f50510e7a78` FOREIGN KEY (`derived_container_id`) REFERENCES `derived_day_assignments_container` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkbb493f50756348a8` FOREIGN KEY (`specific_container_id`) REFERENCES `specific_day_assignments_container` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `dependency`
  ADD CONSTRAINT `fkfe6ed34b1545e7a` FOREIGN KEY (`origin`) REFERENCES `task_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkfe6ed34b9e788f90` FOREIGN KEY (`queue_dependency`) REFERENCES `limiting_resource_queue_dependency` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkfe6ed34be838f362` FOREIGN KEY (`destination`) REFERENCES `task_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `derived_allocation`
  ADD CONSTRAINT `fkf0260c4275ed79ba` FOREIGN KEY (`resource_allocation_id`) REFERENCES `resource_allocation` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkf0260c4287b470f0` FOREIGN KEY (`configurationunit`) REFERENCES `machine_workers_configuration_unit` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `derived_day_assignments_container`
  ADD CONSTRAINT `fkb83176c31b8e7cf2` FOREIGN KEY (`derived_allocation_id`) REFERENCES `derived_allocation` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkb83176c3421c7cf4` FOREIGN KEY (`scenario`) REFERENCES `scenario` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `description_values`
  ADD CONSTRAINT `fk7d1ee2c5fec79eb0` FOREIGN KEY (`description_value_id`) REFERENCES `work_report` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `description_values_in_line`
  ADD CONSTRAINT `fk1e6bf5475c390c4` FOREIGN KEY (`description_value_id`) REFERENCES `work_report_line` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `direct_advance_assignment`
  ADD CONSTRAINT `fk172a16c02f2d3aec` FOREIGN KEY (`advance_assignment_id`) REFERENCES `advance_assignment` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk172a16c0a1127ce5` FOREIGN KEY (`direct_order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `expense_sheet_line`
  ADD CONSTRAINT `expense_sheet_line_expense_sheet_fkey` FOREIGN KEY (`expense_sheet_id`) REFERENCES `expense_sheet` (`id`),
  ADD CONSTRAINT `expense_sheet_line_order_element_fkey` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`),
  ADD CONSTRAINT `expense_sheet_line_resource_fkey` FOREIGN KEY (`resource_id`) REFERENCES `resource` (`id`);

ALTER TABLE `external_company`
  ADD CONSTRAINT `fkd8e14c09b36a6d51` FOREIGN KEY (`company_user`) REFERENCES `user_table` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `generic_day_assignments_container`
  ADD CONSTRAINT `fkc01655fd421c7cf4` FOREIGN KEY (`scenario`) REFERENCES `scenario` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkc01655fdee970b` FOREIGN KEY (`resource_allocation_id`) REFERENCES `generic_resource_allocation` (`resource_allocation_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `generic_resource_allocation`
  ADD CONSTRAINT `fkf788b34975ed79ba` FOREIGN KEY (`resource_allocation_id`) REFERENCES `resource_allocation` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `heading_field`
  ADD CONSTRAINT `fk2908787d415884f6` FOREIGN KEY (`heading_id`) REFERENCES `work_report_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `hours_group`
  ADD CONSTRAINT `fkd9b7594f1ed629ea` FOREIGN KEY (`parent_order_line`) REFERENCES `order_line` (`order_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkd9b7594f8bdc6ac6` FOREIGN KEY (`order_line_template`) REFERENCES `order_line_template` (`order_line_template_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `hour_cost`
  ADD CONSTRAINT `fk3b9a8148c29ad8eb` FOREIGN KEY (`cost_category_id`) REFERENCES `cost_category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk3b9a8148d5b6184d` FOREIGN KEY (`type_of_work_hours_id`) REFERENCES `type_of_work_hours` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `indirect_advance_assignment`
  ADD CONSTRAINT `fk64cbad3b218d7620` FOREIGN KEY (`indirect_order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk64cbad3b2f2d3aec` FOREIGN KEY (`advance_assignment_id`) REFERENCES `advance_assignment` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk64cbad3b8202350f` FOREIGN KEY (`indirect_order_element_id`) REFERENCES `order_line_group` (`order_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `label`
  ADD CONSTRAINT `fk61f7ef4707cd777` FOREIGN KEY (`label_type_id`) REFERENCES `label_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `limiting_resource_queue`
  ADD CONSTRAINT `fk7e57469848d21790` FOREIGN KEY (`resource_id`) REFERENCES `resource` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `limiting_resource_queue_dependency`
  ADD CONSTRAINT `fk5948535228f2695` FOREIGN KEY (`origin_queue_element_id`) REFERENCES `limiting_resource_queue_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk59485352e42f8d29` FOREIGN KEY (`destiny_queue_element_id`) REFERENCES `limiting_resource_queue_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `limiting_resource_queue_element`
  ADD CONSTRAINT `fk1fc5f45575ed79ba` FOREIGN KEY (`resource_allocation_id`) REFERENCES `resource_allocation` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk1fc5f455bd2209e8` FOREIGN KEY (`limiting_resource_queue_id`) REFERENCES `limiting_resource_queue` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `line_field`
  ADD CONSTRAINT `fk88eecef415884f6` FOREIGN KEY (`heading_id`) REFERENCES `work_report_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `machine`
  ADD CONSTRAINT `fk31314447937680b7` FOREIGN KEY (`machine_id`) REFERENCES `resource` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `machine_configuration_unit_required_criterions`
  ADD CONSTRAINT `fk95548d7861f02c44` FOREIGN KEY (`criterion_id`) REFERENCES `criterion` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk95548d7875999a91` FOREIGN KEY (`id`) REFERENCES `machine_workers_configuration_unit` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `machine_workers_configuration_unit`
  ADD CONSTRAINT `fkd47281efffeb5538` FOREIGN KEY (`machine`) REFERENCES `machine` (`machine_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `machine_worker_assignment`
  ADD CONSTRAINT `fka2c1583686b2de7a` FOREIGN KEY (`configuration_id`) REFERENCES `machine_workers_configuration_unit` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fka2c158369bebcf10` FOREIGN KEY (`worker_id`) REFERENCES `worker` (`worker_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `manual_function`
  ADD CONSTRAINT `mnual_function_assignment_function_fkey` FOREIGN KEY (`assignment_function_id`) REFERENCES `assignment_function` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `material`
  ADD CONSTRAINT `fk11d365279578651e` FOREIGN KEY (`category_id`) REFERENCES `material_category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk11d36527f11b2d0` FOREIGN KEY (`unit_type`) REFERENCES `unit_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `material_assigment`
  ADD CONSTRAINT `fkb3e9425b5c68337` FOREIGN KEY (`material_id`) REFERENCES `material` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkb3e9425efda874f` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `material_assigment_template`
  ADD CONSTRAINT `fk3525435419b9dfde` FOREIGN KEY (`order_element_template_id`) REFERENCES `order_element_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk35254354b5c68337` FOREIGN KEY (`material_id`) REFERENCES `material` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `material_category`
  ADD CONSTRAINT `fk84c66516b53669f2` FOREIGN KEY (`parent_id`) REFERENCES `material_category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_authorization`
  ADD CONSTRAINT `fkb92b59485567ad13` FOREIGN KEY (`user_id`) REFERENCES `user_table` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkb92b594887287288` FOREIGN KEY (`order_id`) REFERENCES `order_table` (`order_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkb92b5948edc4db41` FOREIGN KEY (`profile_id`) REFERENCES `profile_table` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_element`
  ADD CONSTRAINT `fk92271f0b1e635c19` FOREIGN KEY (`parent`) REFERENCES `order_line_group` (`order_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk92271f0bd97bcc8c` FOREIGN KEY (`template`) REFERENCES `order_element_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_element_label`
  ADD CONSTRAINT `fke8344cc0c1c2746e` FOREIGN KEY (`label_id`) REFERENCES `label` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fke8344cc0efda874f` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_element_template`
  ADD CONSTRAINT `fk4339b2e41638aab` FOREIGN KEY (`parent`) REFERENCES `order_line_group_template` (`group_template_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_element_template_label`
  ADD CONSTRAINT `fk616de2a319b9dfde` FOREIGN KEY (`order_element_template_id`) REFERENCES `order_element_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk616de2a3c1c2746e` FOREIGN KEY (`label_id`) REFERENCES `label` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_element_template_quality_form`
  ADD CONSTRAINT `fkfe6fb57519b9dfde` FOREIGN KEY (`order_element_template_id`) REFERENCES `order_element_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkfe6fb5758b37665c` FOREIGN KEY (`quality_form_id`) REFERENCES `quality_form` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_line`
  ADD CONSTRAINT `fk2d124245efda874f` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_line_group`
  ADD CONSTRAINT `fkdce41405efda874f` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_line_group_template`
  ADD CONSTRAINT `fk9c819f74ddc82952` FOREIGN KEY (`group_template_id`) REFERENCES `order_element_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_line_template`
  ADD CONSTRAINT `fke4c379349fb7fc18` FOREIGN KEY (`order_line_template_id`) REFERENCES `order_element_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_sync_info`
  ADD CONSTRAINT `order_sync_info_order_table_fkey` FOREIGN KEY (`order_element_id`) REFERENCES `order_table` (`order_element_id`);

ALTER TABLE `order_table`
  ADD CONSTRAINT `fk75a2f39d4ec080cf` FOREIGN KEY (`customer`) REFERENCES `external_company` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk75a2f39d504f463e` FOREIGN KEY (`order_element_id`) REFERENCES `order_line_group` (`order_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk75a2f39da44abee3` FOREIGN KEY (`base_calendar_id`) REFERENCES `base_calendar` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_template`
  ADD CONSTRAINT `fk6476ce4b9a4a7d90` FOREIGN KEY (`order_template_id`) REFERENCES `order_line_group_template` (`group_template_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk6476ce4ba44abee3` FOREIGN KEY (`base_calendar_id`) REFERENCES `base_calendar` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order_version`
  ADD CONSTRAINT `fka391ce7a2380ca7` FOREIGN KEY (`ownerscenario`) REFERENCES `scenario` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `planning_data`
  ADD CONSTRAINT `fkbb58534c6ccf87c5` FOREIGN KEY (`planning_data_id`) REFERENCES `task_group` (`task_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `profile_roles`
  ADD CONSTRAINT `fkd557d8a7edc4db41` FOREIGN KEY (`profile_id`) REFERENCES `profile_table` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `quality_form`
  ADD CONSTRAINT `fkf635cc04b216ed4c` FOREIGN KEY (`advance_type_id`) REFERENCES `advance_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `quality_form_items`
  ADD CONSTRAINT `fkad6003c58b37665c` FOREIGN KEY (`quality_form_id`) REFERENCES `quality_form` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `resource`
  ADD CONSTRAINT `fkebabc40edc874c20` FOREIGN KEY (`base_calendar_id`) REFERENCES `resource_calendar` (`base_calendar_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `resources_cost_category_assignment`
  ADD CONSTRAINT `fk27c2a21648d21790` FOREIGN KEY (`resource_id`) REFERENCES `resource` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk27c2a216c29ad8eb` FOREIGN KEY (`cost_category_id`) REFERENCES `cost_category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `resource_allocation`
  ADD CONSTRAINT `fke8a96db115671e92` FOREIGN KEY (`assignment_function`) REFERENCES `assignment_function` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fke8a96db1ff61540d` FOREIGN KEY (`task`) REFERENCES `task` (`task_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `resource_calendar`
  ADD CONSTRAINT `fk9619184fa44abee3` FOREIGN KEY (`base_calendar_id`) REFERENCES `base_calendar` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `roles_table`
  ADD CONSTRAINT `fk2e7e6bcc5567ad13` FOREIGN KEY (`user_id`) REFERENCES `user_table` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `scenario`
  ADD CONSTRAINT `fkd1c57390fd99606d` FOREIGN KEY (`predecessor`) REFERENCES `scenario` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `scenario_orders`
  ADD CONSTRAINT `fk91bbca7423b85cf1` FOREIGN KEY (`order_version_id`) REFERENCES `order_version` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk91bbca7487287288` FOREIGN KEY (`order_id`) REFERENCES `order_table` (`order_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk91bbca74c0fb9d8e` FOREIGN KEY (`scenario_id`) REFERENCES `scenario` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `scheduling_data_for_version`
  ADD CONSTRAINT `fk672eed98efda874f` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `scheduling_states_by_order_version`
  ADD CONSTRAINT `fk84f61df123b85cf1` FOREIGN KEY (`order_version_id`) REFERENCES `order_version` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk84f61df19bfe55d0` FOREIGN KEY (`scheduling_state_for_version_id`) REFERENCES `scheduling_data_for_version` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk84f61df1efda874f` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `sigmoid_function`
  ADD CONSTRAINT `fkc9c3fe691a5e11f8` FOREIGN KEY (`assignment_function_id`) REFERENCES `assignment_function` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `specific_day_assignments_container`
  ADD CONSTRAINT `fkcee46998421c7cf4` FOREIGN KEY (`scenario`) REFERENCES `scenario` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkcee469987518838c` FOREIGN KEY (`resource_allocation_id`) REFERENCES `specific_resource_allocation` (`resource_allocation_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `specific_resource_allocation`
  ADD CONSTRAINT `fkf0e8572475ed79ba` FOREIGN KEY (`resource_allocation_id`) REFERENCES `resource_allocation` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkf0e85724eae850b2` FOREIGN KEY (`resource`) REFERENCES `resource` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `stretches`
  ADD CONSTRAINT `fkee374673ae0677b8` FOREIGN KEY (`assignment_function_id`) REFERENCES `stretches_function` (`assignment_function_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `stretches_function`
  ADD CONSTRAINT `fk4949f0241a5e11f8` FOREIGN KEY (`assignment_function_id`) REFERENCES `assignment_function` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `subcontracted_task_data`
  ADD CONSTRAINT `fk35bc4ed63804cfa` FOREIGN KEY (`external_company`) REFERENCES `external_company` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `sum_charged_effort`
  ADD CONSTRAINT `sum_charged_effort_order_element_fkey` FOREIGN KEY (`order_element`) REFERENCES `order_element` (`id`);

ALTER TABLE `sum_expenses`
  ADD CONSTRAINT `sum_expenses_order_element_fkey` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`);

ALTER TABLE `task`
  ADD CONSTRAINT `fk3635854936bb8c` FOREIGN KEY (`task_element_id`) REFERENCES `task_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk3635855b595a0` FOREIGN KEY (`subcontrated_task_data_id`) REFERENCES `subcontracted_task_data` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `task_element`
  ADD CONSTRAINT `fkc631a642a44abee3` FOREIGN KEY (`base_calendar_id`) REFERENCES `base_calendar` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkc631a642a5f3c581` FOREIGN KEY (`parent`) REFERENCES `task_group` (`task_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `task_group`
  ADD CONSTRAINT `fk4d9497454936bb8c` FOREIGN KEY (`task_element_id`) REFERENCES `task_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `task_milestone`
  ADD CONSTRAINT `fkd04de7364936bb8c` FOREIGN KEY (`task_element_id`) REFERENCES `task_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `task_quality_form`
  ADD CONSTRAINT `fk4356e07e8b37665c` FOREIGN KEY (`quality_form_id`) REFERENCES `quality_form` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk4356e07eefda874f` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `task_quality_form_items`
  ADD CONSTRAINT `fk101a54bf87fa6b5d` FOREIGN KEY (`task_quality_form_id`) REFERENCES `task_quality_form` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `task_source`
  ADD CONSTRAINT `fk7950e0153d72bc6f` FOREIGN KEY (`id`) REFERENCES `task_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk7950e0159a2c0abd` FOREIGN KEY (`schedulingdata`) REFERENCES `scheduling_data_for_version` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `task_source_hours_groups`
  ADD CONSTRAINT `fka01fe4ee8c80ccb7` FOREIGN KEY (`task_source_id`) REFERENCES `task_source` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fka01fe4eee036cfed` FOREIGN KEY (`hours_group_id`) REFERENCES `hours_group` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `user_profiles`
  ADD CONSTRAINT `fkc74605de5567ad13` FOREIGN KEY (`user_id`) REFERENCES `user_table` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkc74605deedc4db41` FOREIGN KEY (`profile_id`) REFERENCES `profile_table` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `user_table`
  ADD CONSTRAINT `fk7358465a4cd98327` FOREIGN KEY (`lastconnectedscenario`) REFERENCES `scenario` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `user_criterion_fkey` FOREIGN KEY (`resources_load_filter_criterion_id`) REFERENCES `criterion` (`id`) ON DELETE SET NULL,
  ADD CONSTRAINT `user_label_fkey` FOREIGN KEY (`projects_filter_label_id`) REFERENCES `label` (`id`) ON DELETE SET NULL;

ALTER TABLE `virtual_worker`
  ADD CONSTRAINT `fkee053f32f2ed6dc` FOREIGN KEY (`virtual_worker_id`) REFERENCES `worker` (`worker_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `worker`
  ADD CONSTRAINT `fkd162537e40901220` FOREIGN KEY (`worker_id`) REFERENCES `resource` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `worker_user_fkey` FOREIGN KEY (`user_id`) REFERENCES `user_table` (`id`);

ALTER TABLE `workreportslines_labels`
  ADD CONSTRAINT `fkcb8fc1cd5078e161` FOREIGN KEY (`work_report_line_id`) REFERENCES `work_report_line` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkcb8fc1cdc1c2746e` FOREIGN KEY (`label_id`) REFERENCES `label` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `workreports_labels`
  ADD CONSTRAINT `fkf796fbd0c1c2746e` FOREIGN KEY (`label_id`) REFERENCES `label` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkf796fbd0f1a3177c` FOREIGN KEY (`work_report_id`) REFERENCES `work_report` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `work_report`
  ADD CONSTRAINT `fkfd7aa62248d21790` FOREIGN KEY (`resource_id`) REFERENCES `resource` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkfd7aa62278e4e2ea` FOREIGN KEY (`ork_report_type_id`) REFERENCES `work_report_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkfd7aa622efda874f` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `work_report_label_type_assigment`
  ADD CONSTRAINT `fkbb262920131853a1` FOREIGN KEY (`work_report_type_id`) REFERENCES `work_report_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkbb262920707cd777` FOREIGN KEY (`label_type_id`) REFERENCES `label_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fkbb262920c1c2746e` FOREIGN KEY (`label_id`) REFERENCES `label` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `work_report_line`
  ADD CONSTRAINT `fke2af47f148d21790` FOREIGN KEY (`resource_id`) REFERENCES `resource` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fke2af47f1e7e1020b` FOREIGN KEY (`type_work_hours_id`) REFERENCES `type_of_work_hours` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fke2af47f1efda874f` FOREIGN KEY (`order_element_id`) REFERENCES `order_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fke2af47f1f1a3177c` FOREIGN KEY (`work_report_id`) REFERENCES `work_report` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;